name: Preprocessing Dataset

on:
  push:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Riyana.py

      - name: Upload preprocessing artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dataset_preprocessing
          path: preprocessing/dataset_preprocessing